name: firebase_core
description: A new Flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: '>=2.5.0'

dependencies:
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ffigen: ^7.2.6

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: FirebaseCorePlugin

ffigen:
  output: 'generated_bindings.dart'
  headers:
    entry-points:
      - 'firebase/app.h'
    include-directives:
      - 'firebase/**.h'
