name: firebase_storage_example
description: Demonstrates how to use the firebase_storage plugin.

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  firebase_core: any
  firebase_storage: any
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+4
  image_picker_for_web: ^2.1.4
  shared_preferences: ^2.0.17

flutter:
  uses-material-design: true
  assets:
    - assets/hello.txt
