name: flutterfire_ui_oauth_twitter
description: Twitter Sign In for FlutterFire UI
version: 0.1.0
repository: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/flutterfire_ui_oauth_twitter
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/flutterfire_ui_oauth_twitter

environment:
  sdk: '>=2.16.2 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^3.3.17
  flutterfire_ui_oauth: ^0.1.0
  twitter_login: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/twitter_icon.svg
